### ISSUE TITLE
Collaboration #1: Jake Pickett

### ISSUE THREAD

**Issue by sonianara** [cpe305/fall2016-project-sonianara#1]
@jakep11: Please create a class called **Random**.

In this class, create an array of 100 letters in the following distribution (ignore the points for now): 
     - 2 blank tiles (scoring 0 points)
     - 1 point: E ×12, A ×9, I ×9, O ×8, N ×6, R ×6, T ×6, L ×4, S ×4, U ×4
     - 2 points: D ×4, G ×3
     - 3 points: B ×2, C ×2, M ×2, P ×2
     - 4 points: F ×2, H ×2, V ×2, W ×2, Y ×2
     - 5 points: K ×1
     - 8 points: J ×1, X ×1
     - 10 points: Q ×1, Z ×1

**Methods**:
     - getRandomLetter(): char
     - getFullSet(): ArrayList<char> of size 7

**Comment by jakep11** [comment]
I'm going to create a Letter class as well instead of using a char for the letters

**Comment by jakep11** [comment]
Created a class called RandomLetters instead of Random because of a namespace conflict with the Java Random class. I created a Letter class as well. I added the point values as well.
